name: Sample-book-app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          port: 2345
          enviroment: 'DEV'

      - name: ... buil success ...
        run: echo Building of node application is starting ..

      - name: ... check node version ...
        run: node -v 
     
      - name: ...check node and npm versions...
        run:
         npm -v
         node -v
    
  deploy-dev:
    name: Deploy
    runs-on: self-hosted
    needs: [build]

    steps:
      - name: ... deploy success ...
        run: echo Deplyment to DEV has started ..   

  tests-dev:
    name: Tests
    runs-on: self-hosted
    needs: [deploy-dev]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'ReinisVelmeris/api-automation'
          path: 'api-tests'
      - uses: ./.github/actions/test
        with:
          enviroment: 'DEV'

  deploy-stg:
    name: Deploy
    runs-on: self-hosted
    needs: [tests-dev]

    steps:
      - name: ... deploy success ...
        run: echo Deplyment to STG has started ..   

  tests-stg:
    name: Tests
    runs-on: self-hosted
    needs: [deploy-stg]

    steps:
      - name: ... tests success ...
        run: echo Testing on STG has started ..

  deploy-prd:
    name: Deploy
    runs-on: self-hosted
    needs: [tests-stg]

    steps:
      - name: ... deploy success ...
        run: echo Deplyment to PRD has started ..   

  tests-prd:
    name: Tests
    runs-on: self-hosted
    needs: [deploy-prd]

    steps:
      - name: ... tests success ...
        run: echo Testing on PRD has started ..